#!/bin/bash
#
# By Lorenzo Sonnino
#

# Basic config and default values
CONFIG_FILE_PATH="/etc/ot-user.config"

# Create the config file
function create_config {
    echo -e "# The folder containing all the home folders of all the temporary users" >> $CONFIG_FILE_PATH
    echo -e "#ONE_TIME_HOME=temporary" >> $CONFIG_FILE_PATH
    echo -e "# The group containing all the temporary users" >> $CONFIG_FILE_PATH
    echo -e "#ONE_TIME_GROUP=temporaryuser" >> $CONFIG_FILE_PATH
    echo -e "# The file containing the user names of all the temporary users" >> $CONFIG_FILE_PATH
    echo -e "# WARNING: if changed, make sure to paste the content of the old TEMP_USERS_FILE in the new one" >> $CONFIG_FILE_PATH
    echo -e "#TEMP_USERS_FILE='/root/temporary_users.txt'" >> $CONFIG_FILE_PATH
    echo -e "# The number of characters defining a user. Must be large enough to avoid collisions" >> $CONFIG_FILE_PATH
    echo -e "#USERNAME_LENGTH=8" >> $CONFIG_FILE_PATH
    echo -e "# The number of characters defining a user's password" >> $CONFIG_FILE_PATH
    echo -e "#PASSWORD_LENGTH=8" >> $CONFIG_FILE_PATH
}

# Check if config file exists
if [[ ! -f $CONFIG_FILE_PATH ]]
then
    create_config
fi

# Set default values
ONE_TIME_HOME=temporary
ONE_TIME_GROUP=temporaryuser
TEMP_USERS_FILE='/root/temporary_users.txt'
USERNAME_LENGTH=8
PASSWORD_LENGTH=8

# Read the config file
. $CONFIG_FILE_PATH

# Create temporary users home folders
mkdir -p /home/$ONE_TIME_HOME

# Create file to store temporary users in
if [[ ! -f $TEMP_USERS_FILE ]]
then
    touch $TEMP_USERS_FILE
fi

# Create temporary users group
if ! grep -q $ONE_TIME_GROUP /etc/group
then
    addgroup $ONE_TIME_GROUP
fi

# Create a new temporary user
function create {
    # Get a random username and a random password
    USER_NAME=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $USERNAME_LENGTH | head -n 1)
    PASSWORD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $PASSWORD_LENGTH | head -n 1)

    # Create user
    sudo useradd -s /bin/rbash -d /home/$ONE_TIME_HOME/$USER_NAME/ -m -G $ONE_TIME_GROUP -p $(openssl passwd -crypt $PASSWORD) $USER_NAME

    # Register the user to be deleted
    echo $USER_NAME >> $TEMP_USERS_FILE

    # Display information to the user
    echo -e "Created user:"
    echo -e "username: \t "$USER_NAME
    echo -e "password: \t "$PASSWORD
}

# Clear all temporary users
function clear {
    # Get all temporary users
    while IFS= read -r USER_NAME
    do
        # Force the user to log out
        sudo pkill -KILL -u $(id -u $USER_NAME)
        # Delete the user
        sudo userdel -f -r $USER_NAME
    done < $TEMP_USERS_FILE

    # Empty file
    sudo rm $TEMP_USERS_FILE
    sudo touch $TEMP_USERS_FILE
}

# List all the temporary users
function list {
    # Get all temporary users
    while IFS= read -r USER_NAME
    do
        # Display it
        echo $USER_NAME
    done < $TEMP_USERS_FILE
}

# Display help message
function help {
    echo -e "Usage: ot-user [command]"
    echo -e ""
    echo -e "Commands:"
    echo -e "\t clear:  \t Clear all the created temporary users"
    echo -e "\t create: \t Create a new temporary user"
    echo -e "\t help:   \t Display this help message"
    echo -e "\t list:   \t List all the temporary users"
    echo -e ""
}

# Parse arguments
case $1 in
    "clear")
        clear
    ;;
    "create")
        create
    ;;
    "help")
        help
    ;;
    "list")
        list
    ;;
    *)
        help
    ;;
esac
